In [4]:
import numpy as np
#import tensorflow as tf
import scipy.sparse as sp
#tf.enable_eager_execution()
import torch

In [2]:
adj = np.array([[50.0,0],[0,100.0]])
recs = np.array([[0.3,0.4],[0.5,0.6]])

In [5]:
orig_coo = sp.coo_matrix(adj)
x_ind, y_ind, original = orig_coo.row, orig_coo.col, orig_coo.data 
print(x_ind, y_ind, original)
inds = zip(x_ind, y_ind)

(array([0, 1], dtype=int32), array([0, 1], dtype=int32), array([ 50., 100.]))


In [7]:
t_original = torch.FloatTensor(original)
t_logX = torch.log(t_original)
print(t_logX)

tensor([3.9120, 4.6052])


In [24]:
logX = tf.log(original)
print(logX)

tf.Tensor([3.91202301 4.60517019], shape=(2,), dtype=float64)


In [8]:
t_recs = torch.FloatTensor(recs)
t_tmp1 = t_recs[x_ind,y_ind]
print(t_tmp1)

tensor([0.3000, 0.6000])


In [22]:
tmp1 = tf.gather_nd(recs,inds)
print(tmp1)

tf.Tensor([0.3 0.6], shape=(2,), dtype=float64)


In [10]:
t_tmp2 = t_recs[x_ind,y_ind] -t_logX
print(t_tmp2)

tensor([-3.6120, -4.0052])


In [23]:
tmp2 = tf.subtract(tf.gather_nd(recs,inds),logX)
print(tmp2)

tf.Tensor([-3.61202301 -4.00517019], shape=(2,), dtype=float64)


In [12]:
t_tmp3 = t_tmp2**2
print(t_tmp3)

tensor([13.0467, 16.0414])


In [25]:
tmp3 = tf.square(tmp2)
print(tmp3)

tf.Tensor([13.04671019 16.04138822], shape=(2,), dtype=float64)


In [13]:
t_fX = torch.pow(torch.clamp(torch.div(t_original,100),0,1),0.75)
t_fX

tensor([0.5946, 1.0000])

In [27]:
fX = tf.pow(tf.clip_by_value(tf.divide(original, 100), 0,1), 0.75)
fX

<tf.Tensor: id=83, shape=(2,), dtype=float64, numpy=array([0.59460356, 1.        ])>

In [14]:
t_tmp4 = t_tmp3*t_fX
t_tmp4

tensor([ 7.7576, 16.0414])

In [26]:
tmp4 = tf.multiply(tmp3,fX)
print(tmp4)

tf.Tensor([ 7.75762029 16.04138822], shape=(2,), dtype=float64)


In [16]:
t_tmp5 = torch.mean(t_tmp4)
t_tmp5

tensor(11.8995)

In [28]:
tmp5 = tf.reduce_mean(tmp4)
tmp5

<tf.Tensor: id=86, shape=(), dtype=float64, numpy=11.899504256213522>

In [18]:
torch.mean(((t_recs[x_ind,y_ind] -t_logX)**2)*t_fX)

tensor(11.8995)

In [20]:
tf.reduce_mean(tf.multiply(tf.square(tf.subtract(tf.gather_nd(recs,inds),logX)),fX))


<tf.Tensor: id=55, shape=(), dtype=float64, numpy=11.899504256213522>